name: Clau
favicon: null
layout_spectrum: 0.9317937
typography_spectrum: 0.2765843
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#16160E'
    - '#00A339'
    - '#30EAFF'
    - '#010DFA'
    - '#7715F2'
  brandStrength: 0.5934479
  lightness: 0.2737015
  saturation: 0.0993555
  rhythmicContrast: 0.03525435
purpose: []
